version: "3.11.3"

x-service-volumes: &service-volumes
  - ./:/app/:rw,cached

x-database-variable: &database-variables
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

x-app-variables: &app-variables
  <<: *database-variables
  POSTGRES_HOST: postgres

services:
  website:
    image: hyperohgiridotcom:latest
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes: *service-volumes
    environment: *app-variables
    depends_on:
      - db_migrate
    ports:
      - "8000:8000"
 
  db_migrate:
    image: hyperohgiridotcom:latest
    command: python3 manage.py migrate
    volumes: *service-volumes
    environment: *app-variables
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment: *database-variables
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
