# Generated by Django 5.0 on 2023-12-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinterest_userprofile_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='interest',
            new_name='interests',
        ),
    ]
