# Generated by Django 5.0 on 2024-01-30 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_post_comment_zabuton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='num_zabutons',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.post'),
        ),
    ]
